### ISSUE TITLE
[Suggestion] Profiling plugins

### ISSUE THREAD

**Issue by LordTylus** [TorchAPI/Profiler#12]
Hello there,

It would be absolutely amazing if we would get a way to profile plugins as well.

I mean I dont need to know what exactly its doing but I spent quite some time to figure out that the BlockLimiter seems to be a bit more expensive on huge worlds than anticipated eating up all our simspeed.

Visual Studio cleared that up for me, but since not everyone has the ability to do so it would be super amazing if a !profile plugins would exist.

**Comment by Equinox-** [comment]
This isn't reasonably possible since I can't determine every place that a plugin can possible inject itself into, and adding profiling to the ones I can determine could be very expensive for some plugins.

Mods are similar, but I just profile the session and entity components, which makes it easier.
